### ISSUE TITLE
Crashed calling any method after login

### ISSUE THREAD

**Issue by zlstt** [google/GTMAppAuth#1]
*** Terminating app due to uncaught exception 'Attempted to create a token refresh request from a token response with no refresh token.', reason: 'Attempted to create a token refresh request from a token response with no refresh token.'
When run the Drive Sample, it crashed by calling fetchFileList ([service executeQuery:query
completionHandler:^(GTLRServiceTicket *callbackTicket,
GTLRDrive_FileList *fileList,
NSError *callbackError) { ) :

**Comment by WilliamDenniss** [comment]
Dupe of https://github.com/google/google-api-objectivec-client-for-rest/issues/67
