### ISSUE TITLE
How to get oauthredirect to create kRedirectURI

### ISSUE THREAD

**Issue by mt-lelang** [google/GTMAppAuth#10]
kRedirectURI is created from fomat :
kRedirectURI =  @"com.googleusercontent.apps.YOUR_CLIENT:/oauthredirect";

but, What is oauthredirect ? and how to get it ?
That display error : redirect_uri_mismatch

**Comment by WilliamDenniss** [comment]
Follow the instructions here: https://github.com/google/GTMAppAuth/blob/master/Example-iOS/README.md

You need to register your OAuth client, and will be provided with a client id. You then need to [configure](https://github.com/google/GTMAppAuth/blob/master/Example-iOS/README.md#configure-the-example) the sample in several places with your client ID and redirect URI.
