### ISSUE TITLE
Xcode 12 - Build error for SPM due to the GTMSessionFetcher

### ISSUE THREAD

**Issue by phil1995** [google/GTMAppAuth#106]
Since version 1.5.0 of the `GTMSessionFetcher`, the platforms with their minimum deployment targets are no longer specified in the package manifest, so the minimum deployment target for the `GTMSessionFetcher` under Xcode 12 iOS 9. This is due to the following property of the Swift Package Manager ([Source](https://docs.swift.org/package-manager/PackageDescription/PackageDescription.html)):

> By default, the Swift Package Manager assigns a predefined minimum deployment version for each supported platforms unless configured using the platforms API. This predefined deployment version will be the oldest deployment target version supported by the installed SDK for a given platform.

But since GTMAppAuth has currently specified iOS 8 as minimum deployment target, the build error occurs: 
`The package product 'GTMSessionFetcherCore' requires minimum platform version 9.0 for the iOS platform, but this target supports 8.0`
The build error can be fixed by raising the minimum deployment target for iOS to 9 or (see `GoogleAPIClientForREST 1.5.1`) removing the platforms completely. 
For further information see here: [https://github.com/google/gtm-session-fetcher/issues/215](https://github.com/google/gtm-session-fetcher/issues/215)

**Comment by guidedways** [comment]
Can someone fix this please?

**Comment by ramunasjurgilas** [comment]
I have forked and made fix based on @woxtu fixes.

Branch url: https://github.com/ramunasjurgilas/GTMAppAuth/tree/fix-spm
Package URL: https://github.com/ramunasjurgilas/GTMAppAuth.git
Branch: fix-spm
