### ISSUE TITLE
Could not build Objective-C module 'GTMAppAuth'

### ISSUE THREAD

**Issue by hamermike** [google/GTMAppAuth#107]
Using Swift Package Manager (SPM) I am unable to import GTMAppAuth once a dependency to a default macOS project has been established. When trying to import GTMAppAuth I receive the following error "Could not build Objective-C module 'GTMAppAuth'" and using Xcode 12.0.1. Please see the provided sample (attempting to build will fail).

[GTMAppAuthTestStoryboard.zip](https://github.com/google/GTMAppAuth/files/5514932/GTMAppAuthTestStoryboard.zip)

**Comment by cheif** [comment]
Also bumping into this problem, this seems to be a problem with the headers [`...Authorization.h`, `...KeychainCompatibility.h`] using this snippet: 
```
#if SWIFT_PACKAGE
#import "../GTMAppAuthFetcherAuthorization.h"
#else
#import "GTMAppAuthFetcherAuthorization.h"
#endif
```
Which doesn't seem to have `SWIFT_PACKAGE` set when it's built from XCode, installed through SPM. I'm not really sure which solution would be, but it seems like there might be a problem with this macro in public headers, e.g. [here](https://joesusnick.medium.com/swift-package-manager-with-a-mixed-swift-and-objective-c-project-part-2-2-e71dad234e6#2ffa)

**Comment by non-binary** [comment]
Also experiencing this.

**Comment by ramunasjurgilas** [comment]
I have same problem.
