### ISSUE TITLE
Reference AppAuth in Package.swift

### ISSUE THREAD

**Issue by ChrisPearce** [google/GTMAppAuth#118]
Thank you for the enhancements in #116.

When trying to implement the latest changes, I've noted that the package.swift file currently specifies AppAuthCore as a target dependency.

```
  dependencies: [
      .package(url: "https://github.com/google/gtm-session-fetcher.git", "1.5.0" ..< "2.0.0"),
      .package(url: "https://github.com/openid/AppAuth-iOS.git", "1.4.0" ..< "2.0.0")
  ],
  targets: [
      .target(
          name: "GTMAppAuth",
          dependencies: [
              "GTMSessionFetcherCore",
              "AppAuthCore"
          ],
```

A target dependency to *AppAuth* (rather than just *AppAuthCore*) seems to be required to use a Swift call such as:
```
  self.appDelegate.currentAuthorizationFlow = OIDAuthState.authState(byPresenting: request, presenting: self, callback: {(_ authState: OIDAuthState?, _ error: Error?) -> Void in
      if authState != nil {
          // some code goes here
      }
})
```

A Swift call such as the above seems to be needed as the Objective-C equivalent of the following call:
```
self.appDelegate.currentAuthorizationFlow = [OIDAuthState authStateByPresentingAuthorizationRequest:request callback
```

See the following section of the README of the [openid/App-Auth-iOS](https://github.com/openid/AppAuth-iOS) repository:
<https://github.com/openid/AppAuth-iOS#authorizing-ios>

**Comment by petea** [comment]
GTMAppAuth itself depends only on AppAuthCore (as opposed to the full AppAuth library).  In your implementation, you may want to add a dependency on the full AppAuth library if you need to initiate auth flows or use other methods not included in AppAuthCore.

**Comment by ChrisPearce** [comment]
@petea Thank you for the quick response and clarification

**Comment by IMCHO** [comment]
Is it just me or could it be confusing?
If I need `AppAuth` dependency, I have to folk this repo and edit the `package` file, which makes me unclear.
Why don't you guys provide the perfect `package` or `podspec` file?
