### ISSUE TITLE
iOS example not working

### ISSUE THREAD

**Issue by swissdude** [google/GTMAppAuth#120]
I downloaded this and tried to run the example.

But I get an error saying «AppAuth.h» not found (and indeed, it's not there).

Also, when I try to use this with cocoapods in my app, I can't use `OIDAuthState authStateByPresentingAuthorizationRequest:request presentingViewController:self callback:…` It explicitly requires `authStateByPresentingAuthorizationRequest: request externalUserAgent:userAgent callback:…` 

Either I'm doing something wrong, or your examples and manuals are outdated.

**Comment by petea** [comment]
Which of the two examples are you having trouble with?  Be sure to follow the README.md provided with each.

You'll want to add an explicit AppAuth dependency in your Podfile (in addition to GTMAppAuth) to be able to use all AppAuth methods from your code, as GTMAppAuth only depends on AppAuth/Core.
