### ISSUE TITLE
Is GTMAppAuth considered OAuth OOB flow?

### ISSUE THREAD

**Issue by R4N** [google/GTMAppAuth#156]
We use GTMAppAuth in conjunction with [Google Apis Client Library for Objective-C for Rest](https://github.com/google/google-api-objectivec-client-for-rest) to allow users to link their personal Google Drive and send/receive data to/from it within our iOS and macOS applications.

We recently received an email addressed to Google Developers mentioning that their records indicate we have OAuth clients that used the OAuth OOB flow in the past which they are planning to deprecate in October 3rd, 2022.

We have been using the Google Apis Client Library for a long while and previously it embedded Authorization/Authentication within the project itself. The Authorization/Authentication link on the root project page for the Google Apis Client Library no longer redirects to anything. What's unclear to us, is if our client apps are being flagged because of the previous usage, or if usage of GTMAppAuth is considered OAuth OOB flow and we need to migrate to a different OAuth flow.

This is the blog post that was linked in the email: https://developers.googleblog.com/2022/02/making-oauth-flows-safer.html

Thanks!

Edit:

I do see this redirect uri:
https://github.com/google/GTMAppAuth/blob/3a93fd337c29d986e65211fcf44770559736ce9c/GTMAppAuth/Sources/GTMOAuth2KeychainCompatibility.m#L56

Which looks like it's in the form of  one to the OAuth OOB flow redirect_uri's listed in the blog post, so I suspect that GTMAppAuth is indeed using OAuth OOB flow, is this correct?

**Comment by Timothybas** [comment]
@R4N I too have a same question? Do we need to migrate?

**Comment by R4N** [comment]
I ended up migrating our apps to use [GoogleSignIn](https://github.com/google/GoogleSignIn-iOS) as recommended in the blog post linked.

**Comment by petea** [comment]
[AppAuth](https://github.com/openid/AppAuth-iOS), for which GTMAppAuth is a helper library, does not support the OOB flow.

The [kOOBString constant in GTMOAuth2KeychainCompatibility.m ](https://github.com/google/GTMAppAuth/blob/3a93fd337c29d986e65211fcf44770559736ce9c/GTMAppAuth/Sources/GTMOAuth2KeychainCompatibility.m#L56)you mention above is only used as a placeholder when optionally importing old auth state saved by [GTMOAuth2](https://github.com/google/gtm-oauth2) and isn't relevant here.
