### ISSUE TITLE
Use modern archiving and unarchiving methods in GTMAppAuthFetcherAuthorization.swift

### ISSUE THREAD

**Issue by mdmathias** [google/GTMAppAuth#173]
Due to some archiving bugs, we had to revert back to the older methods for archiving and unarchiving `GTMAppAuthFetcherAuthorization` in Swift. This reversion should only be temporary as there is a fix underway. When ready, update the following:

* `GTMAppAuthFetcherAuthorization.save(authorization:itemName:)` to use `NSKeyedArchiver.archivedData(withRootObject:requiringSecureCoding:)`
* Uncomment the code checking for version availability (to call the modern unarchiving method) in `GTMAppAuthFetcherAuthorizaiton.authorization(itemName:)`

Both of these have commented out code and a link to this issue.

**Comment by petea** [comment]
This is closely related to #105.

**Comment by petea** [comment]
This has been addressed on master branch with #145 and bumping our App Auth min version to 1.6.0.

**Comment by mdmathias** [comment]
Closing per https://github.com/google/GTMAppAuth/pull/182#issue-1395194333
