### ISSUE TITLE
Add support for GTMSessionFetcher 2.x

### ISSUE THREAD

**Issue by paulb777** [google/GTMAppAuth#174]
Firebase's next major version update will require GTMSessionFetcher 2.1 and that's incompatible with the current GTMAppAuth dependency.

Is it possible to support both 1.x and 2.x as dependencies?

Firebase had previously been supporting both via this podspec specification: 

` s.dependency 'GTMSessionFetcher/Core', '>= 1.7', '< 3.0'` 

Integration test failure here : 
https://github.com/firebase/firebase-ios-sdk/runs/7927314766?check_suite_focus=true#step:6:169

**Comment by paulb777** [comment]
Looks like this was implemented in #155 and awaiting the 1.3.1 release.

**Comment by petea** [comment]
Yes, we can ship [1.3.1](https://github.com/google/GTMAppAuth/milestone/4) shortly if needed.

Is there a timeline for the next Firebase major release?  We'll probably want to update GSI's GTMSessionFetcher dependency too.

**Comment by mdmathias** [comment]
@petea can this issue be closed?

**Comment by petea** [comment]
> @petea can this issue be closed?

Yes, this was addressed in 1.3.1.
