### ISSUE TITLE
urn:ietf:wg:oauth:2.0:oob not supported

### ISSUE THREAD

**Issue by guidedways** [google/GTMAppAuth#18]
I realise the library is optimised for Google APIs, however I have successfully used the previous one with other services that support OAuth2 (namely Outlook and Yahoo). Since GTMAppAuth is based on top of AppAuth, it seems the browser title redirect method is not supported. Outlook supports native apps however it does not allow us to specify a custom redirect URL. 

Will the browser title method be supported at all?

**Comment by WilliamDenniss** [comment]
No it won't. This library is for the new browser-tab pattern that is replacing the old webview/oob pattern.

I suggest using GTMOAuth if you need to use webview/oob with another provider. You can use both libraries in the same project. They both support the same session fetcher protocol for authorizing API requests, so only the user authorization need be different.
