### ISSUE TITLE
Swift Examples?

### ISSUE THREAD

**Issue by WillBishop** [google/GTMAppAuth#19]
Will there be any Swift example projects?

The Google tutorials are outdated, using a UIWebView which can no longer be used

**Comment by elsesiy** [comment]
Hey Will, I created a convenient wrapper to use if you're interested.

[https://github.com/elsesiy/GAppAuth](https://github.com/elsesiy/GAppAuth)

**Comment by WillBishop** [comment]
Thanks elsesiy, I've created an Issue in that repo, hope you're able to help!
