### ISSUE TITLE
how can I add scopes for Google Drive REST API

### ISSUE THREAD

**Issue by wangbourne** [google/GTMAppAuth#2]
Google Drive scopes are described in this link: [https://developers.google.com/drive/v2/web/scopes](url), and I tried to add one of scopes into GTMAppAuth iOS demo code, but it does not work (Google Drive related authorization does not come)

```
static NSString *const GoogleDriveScopeProfile = @"https://www.googleapis.com/auth/drive";

OIDAuthorizationRequest *request =
        [[OIDAuthorizationRequest alloc] initWithConfiguration:configuration
                                                      clientId:kClientID
                                                        scopes:@[OIDScopeOpenID, OIDScopeProfile,GoogleDriveScopeProfile]
                                                   redirectURL:redirectURI
                                                  responseType:OIDResponseTypeCode
                                          additionalParameters:nil];
```

**Comment by WilliamDenniss** [comment]
That should definitely work, here's an end-to-end iOS Drive demo: https://github.com/WilliamDenniss/GTMAppAuthDriveExampleiOS and the relevant line is here: https://github.com/WilliamDenniss/GTMAppAuthDriveExampleiOS/blob/master/Source/GTMAppAuthExampleViewController.m#L183

**Comment by wangbourne** [comment]
@WilliamDenniss, you are right, thanks :)

**Comment by Ashu** [comment]
Is there any way of getting username using `OIDScopeProfile`? What data do I get by using `OIDScopeProfile`?
