### ISSUE TITLE
AppAuth: Parameter 'presentingViewController' not found in the function declaration

### ISSUE THREAD

**Issue by RiceLinTW** [google/GTMAppAuth#21]
Got a build error in the file OIDAuthorizationUICoordinatorIOS.h:

`/*! @brief The designated initializer.
    @param presentingViewController The view controller from which to present the
        \SFSafariViewController.
 */
- (nullable instancetype)initWithPresentingViewController:(UIViewController *)parentViewController
    NS_DESIGNATED_INITIALIZER;
`

The parameter 'presentingViewController' seems wrong and AppAuth has already fixed [it](https://github.com/openid/AppAuth-iOS/commit/ffcf3244736dd034fd4e3e4bfc299df30316f605).

**Comment by C4Phone** [comment]
I got the same compilation error. I thought it was because ```pod install``` only installed version 0.1.0 of this library. Are you using the latest version or the version provided by pod?

**Comment by RiceLinTW** [comment]
I think it's because of the dependency version is 0.7.0.

GTMAppAuth.podspec
`  s.dependency 'AppAuth', '~> 0.7.0'`

And the misnamed parameter has been fixed at version 0.8.0 few weeks ago.

I add this in line my podfile to temporary fix this problem
`    pod 'AppAuth', :inhibit_warnings => true`

**Comment by timeflying** [comment]
I add the line 
pod 'AppAuth', :inhibit_warnings => true
but it shows:
library not found for -lAppAuth

**Comment by jeremyclee** [comment]
This issue was resolved in version 0.8.0 I believe. If you're still getting the issue, either your pod is specifying a lower version, or your cocoa pods repo is out of date and you need to run `pod repo update`

**Comment by WilliamDenniss** [comment]
The GTMAppAuth podspec now [requires](https://github.com/google/GTMAppAuth/blob/0.6.1/GTMAppAuth.podspec#L47) AppAuth 0.9.0 or later.

You could require the latest version of GTMAppAuth in your PodFile like:
```
'GTMAppAuth', '>= 0.6.1'
```

That way you'll get an error if you `pod install` and your repo isn't up to date.
