### ISSUE TITLE
Need of required reason API policy

### ISSUE THREAD

**Issue by nadun-grabtaxi** [google/GTMAppAuth#233]
```
[File timestamp APIs](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api#4278393)
./Pods/GTMSessionFetcher/Source/GTMSessionFetcherLogging.m

```
Seems it needs to provide the privacy manifest file to support [Apple's privacy policy change](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api#4278393).

**Comment by mdmathias** [comment]
Thanks for the issue. GTMAppAuth will provide a privacy manifest before Apple's Spring 2024 deadline. For what it's worth, `GTMSessionFetcherLogging` is not a type in this repo. I believe you are looking for [this repo](https://github.com/google/gtm-session-fetcher).

**Comment by nadun-grabtaxi** [comment]
Okay. Thanks for the confirmation.
