### ISSUE TITLE
Privacy Manifest for GTMAppAuth

### ISSUE THREAD

**Issue by dmaclach** [google/GTMAppAuth#235]
Apple recently released a [list of 3rd party SDKs](https://developer.apple.com/support/third-party-SDK-requirements/) that will need to include a privacy manifest by spring 2024. GTMAppAuth is on the list so we need to support our clients by adding a privacy manifest. 

https://developer.apple.com/documentation/bundleresources/privacy_manifest_files?language=objc

**Comment by mdmathias** [comment]
We are working on it. There should be a pull request shortly, and a release thereafter. Thanks for your patience and stay tuned!
