### ISSUE TITLE
KeychainAttribute does not work as expected

### ISSUE THREAD

**Issue by olvrlrnz** [google/GTMAppAuth#236]
**Describe the bug**

Specifying `.useDataProtectionKeychain` and/or `.keychainAccessGroup("<group>")` when creating a `KeychainStore` has no effect on the keychain item.

**To Reproduce**

1. Allocate a store:
    ```swift
    let store = KeychainStore(
        itemName: "foo",
        keychainAttributes: [.useDataProtectionKeychain, .keychainAccessGroup(name: "TEAMID.com.example.foobar")]
    )
    ```
2. Save an `AuthSession`
    ```swift
    try store.save(authSession: auth)
    ```
3. Check the 'Access Control' tab in Keychain Access. There's only an entry for the calling application under 'Always allow access by these applications'.

**Expected behavior**

- Specifying `.useDataProtectionKeychain` saves the item in the 'Local Items' keychain
- Specifying `.keychainAccessGroup` allows members of that group access to the item

**Environment**

- OS: macOS 13.6.3 (22G436)
- Library: `41aba100f28395ebe842cd66e5d371cdd46c6792`

**Additional context**

I believe there's a bug in [`KeychainAttribute.keyName`](https://github.com/google/GTMAppAuth/blob/master/GTMAppAuth/Sources/KeychainStore/KeychainAttribute.swift#L32). It should not return the quoted constants but rather the constants itself. So `kSecUseDataProtectionKeychain` instead of `"kSecUseDataProtectionKeychain"` because `KeychainWrapper` uses the return value as-is to assemble the query dictionary for `SecItem(Add|Delete|CopyMatching)` [here](https://github.com/google/GTMAppAuth/blob/master/GTMAppAuth/Sources/KeychainStore/KeychainHelper.swift#L59)

**Comment by olvrlrnz** [comment]
This quick and dirty fix made it work for me:
[GTMAppAuth.patch](https://github.com/google/GTMAppAuth/files/13989215/GTMAppAuth.patch)

Also, according to Apple [1], passing `accessibility` keys along to `KeychainHelper` (like [here](https://github.com/google/GTMAppAuth/blob/master/GTMAppAuth/Sources/KeychainStore/KeychainStore.swift#L107)) is only supported if `kSecUseDataProtectionKeychain` is set to `true`

[1] [Apple](https://developer.apple.com/documentation/security/ksecattraccessible):
> You can use this attribute for macOS keychain items only if you also set a value of true for the [kSecUseDataProtectionKeychain](https://developer.apple.com/documentation/security/ksecusedataprotectionkeychain) key, the [kSecAttrSynchronizable](https://developer.apple.com/documentation/security/ksecattrsynchronizable) key, or both. For any item marked as synchronizable, the value for the kSecAttrAccessible key may only be one whose name does not end with ThisDeviceOnly, as those cannot sync to another device.

**Comment by mdmathias** [comment]
Hi and thanks for the issue! Since you have a patch, would you mind sending up a pull request for us to take a look at?

**Comment by mdmathias** [comment]
I have drafted https://github.com/google/GTMAppAuth/pull/237 to address this. Still need to do some testing in the example apps and hope to write some unit tests around this issue as well.

**Comment by mdmathias** [comment]
Some visual proof that this draft PR begins to address the issue.

![Screenshot 2024-01-19 at 6 00 28 PM](https://github.com/google/GTMAppAuth/assets/4029922/12b2a75b-74a5-4f79-9cbb-ff303eeb888b)
