### ISSUE TITLE
how to obtain a JWT token (id_token)?

### ISSUE THREAD

**Issue by shankari** [google/GTMAppAuth#28]
In the previous version of the library (gtm-oauth2), there was a way to obtain the JWT token from an authorization object using the `id_token` parameter. I use JWTs for cross-device authentication, so I want to get access to the token and authenticate my requests myself.

```
    // else, the real version
    if (self.currAuth != NULL) {
        if (self.currAuth.canAuthorize) {
            return [self.currAuth.parameters valueForKey:@"id_token"];
        }
    }
```

I don't see a way to do that with this replacement library. In particular, I don't see a `parameters` property for  the `GTMAppAuthFetcherAuthorization`, and I don't see the source code for the `OIDAuthState` object, which is where the rest of the tokens appear to live.

**Comment by shankari** [comment]
to add to my own question, and to add to #3, it looks like there is a way to get the id token using the Google+ sign in library.

```
- (void)signIn:(GIDSignIn *)signIn
didSignInForUser:(GIDGoogleUser *)user
     withError:(NSError *)error {
  // Perform any operations on signed in user here.
  NSString *userId = user.userID;                  // For client-side use only!
  NSString *idToken = user.authentication.idToken; // Safe to send to the server
  NSString *fullName = user.profile.name;
  NSString *givenName = user.profile.givenName;
  NSString *familyName = user.profile.familyName;
  NSString *email = user.profile.email;
  // ...
}
```

**Comment by shankari** [comment]
and to answer my own question, it is an `GIDAuthentication` instead.
I am going to wait a bit to see if there is an answer to this question but otherwise, I might just switch to the google identity sign in libraries instead.
https://developers.google.com/identity/sign-in/ios/api/interface_g_i_d_google_user

**Comment by zboralski** [comment]
@StevenEWright GTMAppAuthFetcherAuthorization.authState.lastTokenResponse.idToken
