### ISSUE TITLE
GTMAppAuth flow breaks if using Google Chrome

### ISSUE THREAD

**Issue by dsanghan** [google/GTMAppAuth#30]
Steps to reproduce (Mac):
1. Ensure default browser is Google Chrome
2. Begin auth flow from app
3. Sign-in to reach the consent page in Chrome
4. Click Allow
5. If opening native callback url via Chrome for the first time, an "Open App" dialogue is shown.
6. Wait until auth page navigates away to google.com and click "Open App"
7. Notice callback URL is not called and flow breaks.

Issue does not happen on Firefox/Safari. I figure this is more of a Chromium bug than an GTMAppAuth bug, but there needs to be a more graceful way of handling this on the client end.

**Comment by dsanghan** [comment]
```
    BOOL openedBrowser = [[NSWorkspace sharedWorkspace] openURLs:@[URL]
                                         withAppBundleIdentifier:kSafariBundleID
                                                         options:0
                                  additionalEventParamDescriptor:nil
                                               launchIdentifiers:nil];
    if (!openedBrowser) {
        openedBrowser = [[NSWorkspace sharedWorkspace] openURL:URL];
    }

```

**Comment by dsanghan** [comment]
Just in case someone else runs into it. Just default it to open with safari instead

**Comment by StevenEWright** [comment]
@dsanghan Would you be willing to make a pull request?

**Comment by grantkemp** [comment]
Hi I added a sample project which included MacOs and swift support. I tested it on Chrome and it worked fine.  The only thing I can think might be causing above is if the Url is not entered correctly into your Info.plist 

#60  has the pull request - feel free to try it if it's still an issue.

**Comment by dsanghan** [comment]
@grantkemp: I'd also opened an issue on chromium. Might have been fixed at their end. I'll recheck and close if needed. Thanks.
