### ISSUE TITLE
Podspec not pushed to trunk

### ISSUE THREAD

**Issue by elsesiy** [google/GTMAppAuth#34]
Hey there,

after getting no response on my [PR](https://github.com/google/GTMAppAuth/pull/23) the repo apparently got updated by Phillip Zsika. He bumped the podspec to [0.6.0](https://github.com/google/GTMAppAuth/commit/780f6a9491b1168ca961d5d625aefa78887edb12) but seemed to have forgotten to push the spec to the cocoapods repo so it can be actually discovered and used.

Can you please update the pod repo in a timely manner so people can start using this library again?!

Jonas

**Comment by StevenEWright** [comment]
@protocol86

**Comment by StevenEWright** [comment]
Closing in favor of existing issue: https://github.com/google/GTMAppAuth/issues/22
