### ISSUE TITLE
Can i get authorization with a Service Account?

### ISSUE THREAD

**Issue by fembrioni** [google/GTMAppAuth#46]
I need to access a Google sheet for update from an iOS App without user intervention (neither for sign-in).

Reading the Google API documentation, i know i must use a Service Account to get authorization. I already generate the service account, but i don't know how to ask for authorization. Can anyone please help me?

Thanks,

Fernando

**Comment by WilliamDenniss** [comment]
I'm afraid GTMAppAuth is a library for 3-legged OAuth (i.e. involving the user, your app, and Google), not 2-legged service-account level OAuth (involving your app and Google only).
