### ISSUE TITLE
Swift Port for this?

### ISSUE THREAD

**Issue by grantkemp** [google/GTMAppAuth#5]
Hi 
Is there a swift port for the example project in the roadmap? - or this project going to be deprecated in favour of the Google Sign In SDK? 
This seems very good and simple to use.

**Comment by WilliamDenniss** [comment]
This library can be used with Swift, it won't be ported to Swift. If you encounter any issues using this library with Swift, I encourage you to report them.

This library was created very recently and there are no plans to deprecate it in favor of the Google Sign-in SDK.
