### ISSUE TITLE
Podspec needs a newer AppAuth

### ISSUE THREAD

**Issue by atomicbird** [google/GTMAppAuth#51]
The current Podspec requires AppAuth 0.9.0:

    s.dependency 'AppAuth', '~> 0.9.0'

This can lead to compile errors due to the availability of `SFSafariViewController`. I first encountered this with Xcode 9.2 but I'm not certain if that's the cause. This is fixed in AppAuth version 0.9.1.

For example, 0.9.0 includes this snippet:

```
@implementation OIDAuthorizationUICoordinatorIOS {
  UIViewController *_presentingViewController;

  BOOL _authorizationFlowInProgress;
  __weak id<OIDAuthorizationFlowSession> _session;
  __weak SFSafariViewController *_safariVC;
}
```

Compilation fails with an error reading `'SFSafariViewController' is partial: introduced in iOS 9.0`. This happens even if the app's deployment target is iOS 10.

In 0.9.1 this is fixed as follows:

```
@implementation OIDAuthorizationUICoordinatorIOS {
  UIViewController *_presentingViewController;

  BOOL _authorizationFlowInProgress;
  __weak id<OIDAuthorizationFlowSession> _session;
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wpartial-availability"
  __weak SFSafariViewController *_safariVC;
  SFAuthenticationSession *_authenticationVC;
#pragma clang diagnostic pop
}
```

**Comment by StevenEWright** [comment]
I believe this is fixed now.
