### ISSUE TITLE
GTMTVAuthorizationCancelBlock has an incorrect block definition

### ISSUE THREAD

**Issue by wyllys66** [google/GTMAppAuth#54]
XCode 9 complains because it is defined as:
typedef void (^GTMTVAuthorizationCancelBlock)();

Instead of 
typedef void (^GTMTVAuthorizationCancelBlock)(void);

the "void" is needed for a function that has no parameters.

**Comment by petea** [comment]
The GTMTV classes have been moved off the master branch.
