### ISSUE TITLE
Compatibility with iOS 10?

### ISSUE THREAD

**Issue by StephenKDS** [google/GTMAppAuth#6]
I've used the code in example and got it working perfectly in iOS 9.3, invoking a normal browser window, navigates to google to sign in / give permissions, then return to app and consume tokens etc.

I've experienced with the exact same code, in iOS 10, when it invokes a normal browser window, it doesn't navigate to google to sign in, just sits with a blank window. nothing happens. its very strange. 

<img width="321" alt="screen shot 2017-01-15 at 10 57 38 pm" src="https://cloud.githubusercontent.com/assets/12429771/21961779/56c1a1a0-db78-11e6-84d5-753046bd5a3e.png">

Any ideas?

**Comment by StephenKDS** [comment]
this bug filed to Apple Development, pretty much sums up the issue I have. https://forums.developer.apple.com/message/175531#175531

**Comment by StephenKDS** [comment]
I have a fix for this, I will clone, fix, commit then create a pull request

**Comment by StevenEWright** [comment]
Is this still an issue?

**Comment by StephenKDS** [comment]
To me yes, and according to that linked Developer Report - it is to others as well. I have kept my updated version of the code, and continued to use. This was decided not to merge my changes into the mainline branch. :-/

**Comment by StevenEWright** [comment]
I see now. The PR was https://github.com/openid/AppAuth-iOS/pull/73

@WilliamDenniss WDYT of this?
