### ISSUE TITLE
GTMTVAuthorizationResponse initWithRequest fails to build with super-class-method-mismatch

### ISSUE THREAD

**Issue by cynistersix** [google/GTMAppAuth#68]
`GTMTVAuthorizationResponse.h:76:62: error: method parameter type 'GTMTVAuthorizationRequest *__strong' does not match super class method parameter type 'OIDAuthorizationRequest *__strong' `

-Wsuper-class-method-mismatch

I recommend removing the init from the header

If warnings are treated as errors this happens

**Comment by petea** [comment]
The GTMTV classes have been moved off the master branch.
