### ISSUE TITLE
Allow sending emails from server by transferring gmail API access token to server from iOS client

### ISSUE THREAD

**Issue by ymotov** [google/GTMAppAuth#7]
Using GTMAppAuth to authenticate iOS client with Gmail and fetch emails. But then I need to transfer accessToken and possibly clientId to server to allow sending emails from the server on behalf of a client. Is that possible / acceptable?

**Comment by StevenEWright** [comment]
These general OAuth questions are more appropriate for StackOverflow, which contains answers to these common questions. In the interest of keeping volunteers' time focused on more pressing issues (like updating the podspec), I'm going to close these issues.
