### ISSUE TITLE
Getting crash on line [GTMOAuth2WindowController webView:resource:willSendRequest:redirectResponse:fromDataSource:]

### ISSUE THREAD

**Issue by moontecholabs** [google/GTMAppAuth#79]
1 | App | GTMOAuth2WindowController.m line 453-[GTMOAuth2WindowController webView:resource:willSendRequest:redirectResponse:fromDataSource:]
-- | -- | --
2 | WebKitLegacy | CallResourceLoadDelegate(void (*)(), WebView*, objc_selector*, objc_object*, objc_object*, objc_object*, objc_object*) + 66
3 | WebKitLegacy | WebFrameLoaderClient::dispatchWillSendRequest(WebCore::DocumentLoader*, unsigned long, WebCore::ResourceRequest&, WebCore::ResourceResponse const&) + 270
4 | WebCore | WebCore::ResourceLoadNotifier::dispatchWillSendRequest(WebCore::DocumentLoader*, unsigned long, WebCore::ResourceRequest&, WebCore::ResourceResponse const&) + 159
5 | WebCore | WebCore::ResourceLoader::willSendRequestInternal(WebCore::ResourceRequest&&, WebCore::ResourceResponse const&, WTF::CompletionHandler<void (WebCore::ResourceRequest&&)>&&) + 1407
6 | WebCore | WebCore::SubresourceLoader::willSendRequestInternal(WebCore::ResourceRequest&&, WebCore::ResourceResponse const&, WTF::CompletionHandler<void (WebCore::ResourceRequest&&)>&&)::$_0::operator()(WTF::CompletionHandler<void (WebCore::ResourceRequest&&)>&&, WebCore::ResourceRequest&&) + 420
7 | WebCore | WebCore::SubresourceLoader::willSendRequestInternal(WebCore::ResourceRequest&&, WebCore::ResourceResponse const&, WTF::CompletionHandler<void (WebCore::ResourceRequest&&)>&&) + 361
8 | WebCore | WebCore::ResourceLoader::init(WebCore::ResourceRequest&&, WTF::CompletionHandler<void (bool)>&&) + 343
9 | WebCore | WebCore::SubresourceLoader::create(WebCore::Frame&, WebCore::CachedResource&, WebCore::ResourceRequest&&, WebCore::ResourceLoaderOptions const&, WTF::CompletionHandler<void (WTF::RefPtr<WebCore::SubresourceLoader, WTF::DumbPtrTraits<WebCore::SubresourceLoader> >&&)>&&) + 166
10 | WebKitLegacy | WebResourceLoadScheduler::loadResource(WebCore::Frame&, WebCore::CachedResource&, WebCore::ResourceRequest&&, WebCore::ResourceLoaderOptions const&, WTF::CompletionHandler<void (WTF::RefPtr<WebCore::SubresourceLoader, WTF::DumbPtrTraits<WebCore::SubresourceLoader> >&&)>&&) + 97
11 | WebCore | WebCore::CachedResource::load(WebCore::CachedResourceLoader&) + 2876
12 | WebCore | WebCore::CachedResourceLoader::requestResource(WebCore::CachedResource::Type, WebCore::CachedResourceRequest&&, WebCore::CachedResourceLoader::ForPreload, WebCore::CachedResourceLoader::DeferOption) + 6815
13 | WebCore | WebCore::CachedResourceLoader::requestIcon(WebCore::CachedResourceRequest&&) + 46
14 | WebCore | WebCore::IconLoader::startLoading() + 409
15 | WebCore | WebCore::DocumentLoader::didGetLoadDecisionForIcon(bool, unsigned long long, unsigned long long) + 158
16 | WebKitLegacy | WebFrameLoaderClient::getLoadDecisionForIcons(WTF::Vector<std::__1::pair<WebCore::LinkIcon&, unsigned long long>, 0ul, WTF::CrashOnOverflow, 16ul> const&) + 325
17 | WebCore | WebCore::DocumentLoader::startIconLoading() + 922
18 | WebCore | WebCore::Document::implicitClose() + 322
19 | WebCore | WebCore::FrameLoader::checkCompleted() + 414
20 | WebCore | WebCore::CachedResourceLoader::loadDone(WebCore::LoadCompletionType, bool) + 68
21 | WebCore | WebCore::SubresourceLoader::didFinishLoading(WebCore::NetworkLoadMetrics const&) + 649
22 | WebCore | WebCore::ResourceLoader::didFinishLoading(WebCore::ResourceHandle*) + 187
23 | WebCore | WTF::Function<void ()>::CallableWrapper<-[WebCoreResourceHandleAsOperationQueueDelegate connectionDidFinishLoading:]::$_7>::call() + 73
24 | JavaScriptCore | WTF::dispatchFunctionsFromMainThread() + 249
25 | Foundation | __NSThreadPerformPerform + 327
26 | CoreFoundation | __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
27 | CoreFoundation | __CFRunLoopDoSource0 + 108
28 | CoreFoundation | __CFRunLoopDoSources0 + 195
29 | CoreFoundation | __CFRunLoopRun + 1219
30 | CoreFoundation | CFRunLoopRunSpecific + 463
31 | HIToolbox | RunCurrentEventLoopInMode + 293
32 | HIToolbox | ReceiveNextEventCommon + 618
33 | HIToolbox | _BlockUntilNextEventMatchingListInModeWithFilter + 64
34 | AppKit | _DPSNextEvent + 997
35 | AppKit | -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1362
36 | AppKit | -[NSApplication run] + 699
37 | AppKit | NSApplicationMain + 780
38 | libdyld.dylib | start + 1

**Comment by petea** [comment]
This sounds like an issue with GTM OAuth 2 rather than GTMAppAuth

https://github.com/google/gtm-oauth2/blob/master/Source/Mac/GTMOAuth2WindowController.m

**Comment by moontecholabs** [comment]
Ok, thanks for reply, so which SDK we can use to resolve this issue?
