### ISSUE TITLE
Error 500 when re-authenticating

### ISSUE THREAD

**Issue by thomzon** [google/GTMAppAuth#8]
Hi,

I have a working example of using this library to receive a Gmail token. Initial flow works really well.
However, if I try to re-authenticate a user, and the app is still indicated as authorized in the user's security settings, I always get an error 500 page from Google.

Error received in Safari is attached.
Can someone tell me what I could have done wrong ?

Here is the code:
`NSURL *issuer = [NSURL URLWithString:@"https://accounts.google.com"];
  [OIDAuthorizationService discoverServiceConfigurationForIssuer:issuer
      completion:^(OIDServiceConfiguration *_Nullable configuration, NSError *_Nullable error) {

    if (!configuration) {
      [self logMessage:@"Error retrieving discovery document: %@", [error localizedDescription]];
      [self setAuthorization:nil];
      return;
    }

    [self logMessage:@"Got configuration: %@", configuration];

    // builds authentication request
	NSArray *scopes = @[
						OIDScopeOpenID,
						@"email",
						@"https://www.googleapis.com/auth/userinfo.profile",
						@"https://mail.google.com",
						@"https://www.google.com/m8/feeds",
						];
    OIDAuthorizationRequest *request =
        [[OIDAuthorizationRequest alloc] initWithConfiguration:configuration
                                                      clientId:kClientID
                                                  clientSecret:kClientSecret
                                                        scopes:scopes
                                                   redirectURL:redirectURI
                                                  responseType:OIDResponseTypeCode
                                          additionalParameters:nil];
	
    // performs authentication request
    self.appDelegate.currentAuthorizationFlow =
        [OIDAuthState authStateByPresentingAuthorizationRequest:request
                            callback:^(OIDAuthState *_Nullable authState,
                                       NSError *_Nullable error) {
      if (authState) {
        GTMAppAuthFetcherAuthorization *authorization =
            [[GTMAppAuthFetcherAuthorization alloc] initWithAuthState:authState];
        [self setAuthorization:authorization];
        [self logMessage:@"Got authorization tokens. Access token: %@",
                         authState.lastTokenResponse.accessToken];
      } else {
        [self setAuthorization:nil];
        [self logMessage:@"Authorization error: %@", [error localizedDescription]];
      }
    }];
  }];`

<img width="639" alt="screen shot 2017-02-13 at 14 04 41" src="https://cloud.githubusercontent.com/assets/697167/22884479/68afaf40-f1f5-11e6-99c8-6559e6ebe46d.png">

**Comment by WilliamDenniss** [comment]
What is the URI that is serving the 500?

**Comment by thomzon** [comment]
Hi,

Thanks for the answer. While trying to reproduce the issue to respond to your question, I realized that the config in the Google Developer Console was wrong. I was using a 'WEB' type client ID, while I should have been using an 'Other' client ID.

Now everything works fine.
