### ISSUE TITLE
Is GTMAppAuth using Google+ OAuth API ? 

### ISSUE THREAD

**Issue by mihirpmehta** [google/GTMAppAuth#80]
We are using GTMAppAuth for our iOS application for Signing in user using Gmail account as well as getting user's basic profile

I get email from Google that 

> Google+ APIs and OAuth requests are being shutdown on March 7, 2019

**Google+ API Name | Version | Method or OAuth Scope
-- | -- | --
 | OAuth | N/A | plus.me**

I am not using Google+ APIs/OAuth directly ... My question is this does GTMAppAuth uses Google+ APIs and OAuth internally ? If yes do i need to change or update anything ? 

Thanks

**Comment by petea** [comment]
GTMAppAuth has no built-in Google+ dependencies.  As long as you're not requesting plus.* scopes and or using Google+ APIs, you will be fine.

**Comment by tobihagemann** [comment]
I'm actually having the same issue and I'm not using the `plus.me` scope. I'm only requesting these scopes: `https://www.googleapis.com/auth/drive` and `email`. I don't know how to get more information/support on this but I can't find any references to `plus.me` in my code.

**Comment by blach** [comment]
I just double-checked my code and also looked at the generated request URL. I definitely only request these scopes: `https://www.googleapis.com/auth/drive openid email`

Yet I still received the email from Google that my project requested the `plus.me` scope.

I must assume that the email is wrong and was sent in error.

**Comment by thomasvl** [comment]
Drive by - are there any other sdks/libraries you use to talk to google services that could be providing the scope via some other api/constant?

**Comment by tobihagemann** [comment]
In my case, not that I'm aware of. I use `GTMAppAuth` for the authentication and `GoogleAPIClientForREST/Drive` incl. `GTMSessionFetcher` for accessing Google Drive. I've searched my whole project for `plus.` and there are no results (not even in the mentioned libraries).

**Comment by blach** [comment]
> In my case, not that I'm aware of. I use `GTMAppAuth` for authentication and `GoogleAPIClientForREST/Drive` incl. `GTMSessionFetcher` for accessing Google Drive. I've searched my whole project for `plus.` and there are no results (not even in the mentioned libraries).

Same here.

**Comment by mihirpmehta** [comment]
I have search my entire code nowhere i can find any reference of **plus.me** ... This is surprising ....
