### ISSUE TITLE
You are giving developers a hard time using pods without reason!

### ISSUE THREAD

**Issue by vassilisw** [google/GTMAppAuth#81]
You FIVE contributors of GOOGLE, please consider removing pods from a framework that supposed to be simple.
Really, what is the reason behind using pods in this frameworks?

**Comment by StevenEWright** [comment]
I’m pretty sure the pods are just an optional convenience.

**Comment by benstahl** [comment]
I don't know if removing Pods is necessary but Swift Package Manager is still not supported, that would be the most modern and convenient option to add. 2 years ago lack of SPM support was understandable, in 2020 it is not.

**Comment by petea** [comment]
I'd be interested in hearing about any negative impacts of providing CocoaPods support so that we can try to mitigate.  However, currently, this is a critical distribution mechanism.

[SPM support](#90) is on the way.
