### ISSUE TITLE
How to logout or disconnect as Google SignIn

### ISSUE THREAD

**Issue by sanhue0302** [google/GTMAppAuth#9]
i only found         
```
[GTMAppAuthFetcherAuthorization removeAuthorizationFromKeychainForName:keychainName];
```

to remove authorization from keychain, but does this means i had logout?

**Comment by WilliamDenniss** [comment]
Kind of. It doesn't actually revoke the OAuth token, but by destroying all copies, the session is effectively terminated.  We could add an explicit revoke API call to GTMAppAuth.

Note that any revocation of the OAuth token wouldn't log the user out of *Google*.

**Comment by sanhue0302** [comment]
how to add a revoke call? is there any document?

**Comment by WilliamDenniss** [comment]
It isn't currently supported by the library, but you can make the REST call manually.

Here are the docs: https://developers.google.com/identity/protocols/OAuth2InstalledApp#tokenrevoke
