### ISSUE TITLE
Support Swift Package Manager

### ISSUE THREAD

**Issue by JonasGessner** [google/GTMAppAuth#90]
Swift Package Manager is now [built into Xcode](https://developer.apple.com/documentation/xcode/creating_a_swift_package_with_xcode) and is already becoming widely adopted by 3rd party libraries. It would be great to see support for SPM here to allow exclusive use of SPM to manage several google dependencies like this, GTLR (https://github.com/google/google-api-objectivec-client-for-rest/issues/296) and GTMSessionFetcher (https://github.com/google/gtm-session-fetcher/issues/157).

**Comment by karimhm** [comment]
This https://github.com/openid/AppAuth-iOS/pull/525 must be done first in order to have Swift Package Manager support in **GTMAppAuth**

**Comment by consuelita** [comment]
Looks like openid/AppAuth-iOS#525 was resolved in release 1.4.0, is there an ETA on addressing this issue now that it is done?

**Comment by vmanot** [comment]
I'd also like to get a sense of the ETA on this.

**Comment by karimhm** [comment]
https://github.com/google/GTMAppAuth/pull/103 Might fix this

**Comment by BarnoTD** [comment]
Hi, newbie here. I see this issue marked as complete but no swiftPM badge in the Readme.md file so I'm a little bit confused. can I use this package with SPM safely or not? Thank you for answering my question.
