### ISSUE TITLE
Pods/GTMAppAuth/Source/GTMAppAuthFetcherAuthorization.h:20:9: fatal error: 'GTMSessionFetcher/GTMSessionFetcher.h' file not found

### ISSUE THREAD

**Issue by shshell** [google/GTMAppAuth#91]
Pods/GTMAppAuth/Source/GTMAppAuthFetcherAuthorization.h:20:9: fatal error: 'GTMSessionFetcher/GTMSessionFetcher.h' file not found 

MacOS 10.13.6
Xcode 10.1
pod 1.8.4
pod file.lock as below

PODS:
  - AppAuth/Core (1.2.0)
  - GoogleAPIClientForREST/Core (1.3.10):
    - GTMSessionFetcher (>= 1.1.7)
  - GoogleAPIClientForREST/Drive (1.3.10):
    - GoogleAPIClientForREST/Core
    - GTMSessionFetcher (>= 1.1.7)
  - GTMAppAuth (1.0.0):
    - AppAuth/Core (~> 1.0)
    - GTMSessionFetcher (~> 1.1)
  - GTMSessionFetcher (1.3.0):
    - GTMSessionFetcher/Full (= 1.3.0)
  - GTMSessionFetcher/Core (1.3.0)
  - GTMSessionFetcher/Full (1.3.0):
    - GTMSessionFetcher/Core (= 1.3.0)

DEPENDENCIES:
  - GoogleAPIClientForREST/Drive
  - GTMAppAuth

SPEC REPOS:
  trunk:
    - AppAuth
    - GoogleAPIClientForREST
    - GTMAppAuth
    - GTMSessionFetcher

**Comment by shshell** [comment]
Build fail for not find GTMSessionFetcher.h in GTMAppAuth

**Comment by derjohng** [comment]
I meet the same issue today. I found that GTMAppAuth use GTMSessionFetcher v1.1, and GoogleToolboxForMac use  GTMSessionFetcher v1.3. This cause issue "Multiple targets match implicit dependency for linker flags"

**Comment by petea** [comment]
Reopen if you're still seeing this.
